# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_vhdl -library xil_defaultlib {
  /home/rafa/Dropbox/Aulas/Pos/2014/LogicaProgramavel/Exemplos/Nexys4_Vivado_Basic/source/Nexys4_Vivado_Basic/Nexys4_Vivado_Basic.srcs/sources_1/new/UART_TX_CTRL.vhd
  /home/rafa/Dropbox/Aulas/Pos/2014/LogicaProgramavel/Exemplos/Nexys4_Vivado_Basic/source/Nexys4_Vivado_Basic/Nexys4_Vivado_Basic.srcs/sources_1/new/RGB_controller.vhd
  /home/rafa/Dropbox/Aulas/Pos/2014/LogicaProgramavel/Exemplos/Nexys4_Vivado_Basic/source/Nexys4_Vivado_Basic/Nexys4_Vivado_Basic.srcs/sources_1/new/debouncer.vhd
  /home/rafa/Dropbox/Aulas/Pos/2014/LogicaProgramavel/Exemplos/Nexys4_Vivado_Basic/source/Nexys4_Vivado_Basic/Nexys4_Vivado_Basic.srcs/sources_1/new/GPIO_Demo.vhd
}
read_xdc /home/rafa/Dropbox/Aulas/Pos/2014/LogicaProgramavel/Exemplos/Nexys4_Vivado_Basic/source/Nexys4_Vivado_Basic/Nexys4_Vivado_Basic.srcs/constrs_1/new/Nexys4_Master.xdc
set_property used_in_implementation false [get_files /home/rafa/Dropbox/Aulas/Pos/2014/LogicaProgramavel/Exemplos/Nexys4_Vivado_Basic/source/Nexys4_Vivado_Basic/Nexys4_Vivado_Basic.srcs/constrs_1/new/Nexys4_Master.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/rafa/Dropbox/Aulas/Pos/2014/LogicaProgramavel/Exemplos/Nexys4_Vivado_Basic/source/Nexys4_Vivado_Basic/Nexys4_Vivado_Basic.cache/wt [current_project]
set_property parent.project_dir /home/rafa/Dropbox/Aulas/Pos/2014/LogicaProgramavel/Exemplos/Nexys4_Vivado_Basic/source/Nexys4_Vivado_Basic [current_project]
catch { write_hwdef -file GPIO_demo.hwdef }
synth_design -top GPIO_demo -part xc7a100tcsg324-1
write_checkpoint GPIO_demo.dcp
report_utilization -file GPIO_demo_utilization_synth.rpt -pb GPIO_demo_utilization_synth.pb
