# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
read_vhdl {
  /home/rafael/Dropbox/Aulas/Pos/2014/Logica_Programavel/Exemplos/7segmentos/source/Nexys4_Vivado_Basic/Nexys4_Vivado_Basic.srcs/sources_1/new/RGB_controller.vhd
  /home/rafael/Dropbox/Aulas/Pos/2014/Logica_Programavel/Exemplos/7segmentos/source/Nexys4_Vivado_Basic/Nexys4_Vivado_Basic.srcs/sources_1/new/controlador_7s.vhd
}
read_xdc /home/rafael/Dropbox/Aulas/Pos/2014/Logica_Programavel/Exemplos/7segmentos/source/Nexys4_Vivado_Basic/Nexys4_Vivado_Basic.srcs/constrs_1/new/Nexys4_Master.xdc
set_property used_in_implementation false [get_files /home/rafael/Dropbox/Aulas/Pos/2014/Logica_Programavel/Exemplos/7segmentos/source/Nexys4_Vivado_Basic/Nexys4_Vivado_Basic.srcs/constrs_1/new/Nexys4_Master.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/rafael/Dropbox/Aulas/Pos/2014/Logica_Programavel/Exemplos/7segmentos/source/Nexys4_Vivado_Basic/Nexys4_Vivado_Basic.data/wt [current_project]
set_property parent.project_dir /home/rafael/Dropbox/Aulas/Pos/2014/Logica_Programavel/Exemplos/7segmentos/source/Nexys4_Vivado_Basic [current_project]
synth_design -top RGB_controller -part xc7a100tcsg324-1
write_checkpoint RGB_controller.dcp
report_utilization -file RGB_controller_utilization_synth.rpt -pb RGB_controller_utilization_synth.pb
