# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Problemas/io_basico.xdc

# Block Designs: bd/uc_GPIO/uc_GPIO.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_GPIO || ORIG_REF_NAME==uc_GPIO}]

# IP: bd/uc_GPIO/ip/uc_GPIO_microblaze_0_0/uc_GPIO_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_GPIO_microblaze_0_0 || ORIG_REF_NAME==uc_GPIO_microblaze_0_0}]

# IP: bd/uc_GPIO/ip/uc_GPIO_dlmb_v10_0/uc_GPIO_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_GPIO_dlmb_v10_0 || ORIG_REF_NAME==uc_GPIO_dlmb_v10_0}]

# IP: bd/uc_GPIO/ip/uc_GPIO_ilmb_v10_0/uc_GPIO_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_GPIO_ilmb_v10_0 || ORIG_REF_NAME==uc_GPIO_ilmb_v10_0}]

# IP: bd/uc_GPIO/ip/uc_GPIO_dlmb_bram_if_cntlr_0/uc_GPIO_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_GPIO_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==uc_GPIO_dlmb_bram_if_cntlr_0}]

# IP: bd/uc_GPIO/ip/uc_GPIO_ilmb_bram_if_cntlr_0/uc_GPIO_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_GPIO_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==uc_GPIO_ilmb_bram_if_cntlr_0}]

# IP: bd/uc_GPIO/ip/uc_GPIO_lmb_bram_0/uc_GPIO_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_GPIO_lmb_bram_0 || ORIG_REF_NAME==uc_GPIO_lmb_bram_0}]

# IP: bd/uc_GPIO/ip/uc_GPIO_microblaze_0_axi_periph_0/uc_GPIO_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_GPIO_microblaze_0_axi_periph_0 || ORIG_REF_NAME==uc_GPIO_microblaze_0_axi_periph_0}]

# IP: bd/uc_GPIO/ip/uc_GPIO_mdm_1_0/uc_GPIO_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_GPIO_mdm_1_0 || ORIG_REF_NAME==uc_GPIO_mdm_1_0}]

# IP: bd/uc_GPIO/ip/uc_GPIO_clk_wiz_1_0/uc_GPIO_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_GPIO_clk_wiz_1_0 || ORIG_REF_NAME==uc_GPIO_clk_wiz_1_0}]

# IP: bd/uc_GPIO/ip/uc_GPIO_rst_clk_wiz_1_100M_0/uc_GPIO_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_GPIO_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==uc_GPIO_rst_clk_wiz_1_100M_0}]

# IP: bd/uc_GPIO/ip/uc_GPIO_axi_gpio_0_1/uc_GPIO_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_GPIO_axi_gpio_0_1 || ORIG_REF_NAME==uc_GPIO_axi_gpio_0_1}]

# IP: bd/uc_GPIO/ip/uc_GPIO_axi_gpio_0_2/uc_GPIO_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_GPIO_axi_gpio_0_2 || ORIG_REF_NAME==uc_GPIO_axi_gpio_0_2}]

# IP: bd/uc_GPIO/ip/uc_GPIO_xbar_0/uc_GPIO_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_GPIO_xbar_0 || ORIG_REF_NAME==uc_GPIO_xbar_0}]

# XDC: bd/uc_GPIO/ip/uc_GPIO_microblaze_0_0/uc_GPIO_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uc_GPIO_microblaze_0_0 || ORIG_REF_NAME==uc_GPIO_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/uc_GPIO/ip/uc_GPIO_microblaze_0_0/uc_GPIO_microblaze_0_0_ooc_debug.xdc

# XDC: bd/uc_GPIO/ip/uc_GPIO_microblaze_0_0/uc_GPIO_microblaze_0_0_ooc.xdc

# XDC: bd/uc_GPIO/ip/uc_GPIO_dlmb_v10_0/uc_GPIO_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uc_GPIO_dlmb_v10_0 || ORIG_REF_NAME==uc_GPIO_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/uc_GPIO/ip/uc_GPIO_dlmb_v10_0/uc_GPIO_dlmb_v10_0_ooc.xdc

# XDC: bd/uc_GPIO/ip/uc_GPIO_ilmb_v10_0/uc_GPIO_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uc_GPIO_ilmb_v10_0 || ORIG_REF_NAME==uc_GPIO_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/uc_GPIO/ip/uc_GPIO_ilmb_v10_0/uc_GPIO_ilmb_v10_0_ooc.xdc

# XDC: bd/uc_GPIO/ip/uc_GPIO_dlmb_bram_if_cntlr_0/uc_GPIO_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/uc_GPIO/ip/uc_GPIO_ilmb_bram_if_cntlr_0/uc_GPIO_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/uc_GPIO/ip/uc_GPIO_lmb_bram_0/uc_GPIO_lmb_bram_0_ooc.xdc

# XDC: bd/uc_GPIO/ip/uc_GPIO_mdm_1_0/uc_GPIO_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uc_GPIO_mdm_1_0 || ORIG_REF_NAME==uc_GPIO_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/uc_GPIO/ip/uc_GPIO_mdm_1_0/uc_GPIO_mdm_1_0_ooc_trace.xdc

# XDC: bd/uc_GPIO/ip/uc_GPIO_mdm_1_0/uc_GPIO_mdm_1_0_ooc.xdc

# XDC: bd/uc_GPIO/ip/uc_GPIO_clk_wiz_1_0/uc_GPIO_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uc_GPIO_clk_wiz_1_0 || ORIG_REF_NAME==uc_GPIO_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/uc_GPIO/ip/uc_GPIO_clk_wiz_1_0/uc_GPIO_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uc_GPIO_clk_wiz_1_0 || ORIG_REF_NAME==uc_GPIO_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/uc_GPIO/ip/uc_GPIO_clk_wiz_1_0/uc_GPIO_clk_wiz_1_0_ooc.xdc

# XDC: bd/uc_GPIO/ip/uc_GPIO_rst_clk_wiz_1_100M_0/uc_GPIO_rst_clk_wiz_1_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_GPIO_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==uc_GPIO_rst_clk_wiz_1_100M_0}]

# XDC: bd/uc_GPIO/ip/uc_GPIO_rst_clk_wiz_1_100M_0/uc_GPIO_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_GPIO_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==uc_GPIO_rst_clk_wiz_1_100M_0}]

# XDC: bd/uc_GPIO/ip/uc_GPIO_rst_clk_wiz_1_100M_0/uc_GPIO_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/uc_GPIO/ip/uc_GPIO_axi_gpio_0_1/uc_GPIO_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uc_GPIO_axi_gpio_0_1 || ORIG_REF_NAME==uc_GPIO_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/uc_GPIO/ip/uc_GPIO_axi_gpio_0_1/uc_GPIO_axi_gpio_0_1_ooc.xdc

# XDC: bd/uc_GPIO/ip/uc_GPIO_axi_gpio_0_1/uc_GPIO_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uc_GPIO_axi_gpio_0_1 || ORIG_REF_NAME==uc_GPIO_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/uc_GPIO/ip/uc_GPIO_axi_gpio_0_2/uc_GPIO_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uc_GPIO_axi_gpio_0_2 || ORIG_REF_NAME==uc_GPIO_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/uc_GPIO/ip/uc_GPIO_axi_gpio_0_2/uc_GPIO_axi_gpio_0_2_ooc.xdc

# XDC: bd/uc_GPIO/ip/uc_GPIO_axi_gpio_0_2/uc_GPIO_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uc_GPIO_axi_gpio_0_2 || ORIG_REF_NAME==uc_GPIO_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/uc_GPIO/ip/uc_GPIO_xbar_0/uc_GPIO_xbar_0_ooc.xdc

# XDC: bd/uc_GPIO/uc_GPIO_ooc.xdc
