# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.cache/wt [current_project]
set_property parent.project_path /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/uc_GPIO.bd
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_microblaze_0_0/uc_GPIO_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_microblaze_0_0/uc_GPIO_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_microblaze_0_0/uc_GPIO_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_dlmb_v10_0/uc_GPIO_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_dlmb_v10_0/uc_GPIO_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_ilmb_v10_0/uc_GPIO_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_ilmb_v10_0/uc_GPIO_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_dlmb_bram_if_cntlr_0/uc_GPIO_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_ilmb_bram_if_cntlr_0/uc_GPIO_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_lmb_bram_0/uc_GPIO_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_mdm_1_0/uc_GPIO_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_mdm_1_0/uc_GPIO_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_mdm_1_0/uc_GPIO_mdm_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_clk_wiz_1_0/uc_GPIO_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_clk_wiz_1_0/uc_GPIO_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_clk_wiz_1_0/uc_GPIO_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_rst_clk_wiz_1_100M_0/uc_GPIO_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_rst_clk_wiz_1_100M_0/uc_GPIO_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_rst_clk_wiz_1_100M_0/uc_GPIO_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_axi_gpio_0_1/uc_GPIO_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_axi_gpio_0_1/uc_GPIO_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_axi_gpio_0_1/uc_GPIO_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_axi_gpio_0_2/uc_GPIO_axi_gpio_0_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_axi_gpio_0_2/uc_GPIO_axi_gpio_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_axi_gpio_0_2/uc_GPIO_axi_gpio_0_2.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/ip/uc_GPIO_xbar_0/uc_GPIO_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/uc_GPIO_ooc.xdc]
set_property is_locked true [get_files /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/uc_GPIO.bd]

read_vhdl -library xil_defaultlib {
  /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/bd/uc_GPIO/hdl/uc_GPIO_wrapper.vhd
  /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Exemplos/uc/uc/uc.srcs/sources_1/new/toplevel.vhd
}
read_xdc /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Problemas/io_basico.xdc
set_property used_in_implementation false [get_files /home/Dados/Seafile/Aulas/Pos/Logica-Programavel/Aulas/Problemas/io_basico.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top toplevel -part xc7a100tcsg324-1
write_checkpoint -noxdef toplevel.dcp
catch { report_utilization -file toplevel_utilization_synth.rpt -pb toplevel_utilization_synth.pb }
