# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -id {Synth 8-2778}  -suppress 
set_msg_config  -id {Common 17-69}  -string {{ERROR: [Common 17-69] Command failed: Synthesis failed - please see the console or run log file for details}}  -suppress 
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_vhdl -library xil_defaultlib /home/rafa/Dropbox/Aulas/Pos/2014/LogicaProgramavel/Exemplos/05-Concorrente/05-Mux-Simples/Mux-Simples.srcs/sources_1/toplevel-mux.vhd
read_xdc /home/rafa/Dropbox/Aulas/Pos/2014/LogicaProgramavel/Exemplos/05-Concorrente/05-Mux-Simples/Mux-Simples.srcs/constrs_1/new/Nexys4_Master.xdc
set_property used_in_implementation false [get_files /home/rafa/Dropbox/Aulas/Pos/2014/LogicaProgramavel/Exemplos/05-Concorrente/05-Mux-Simples/Mux-Simples.srcs/constrs_1/new/Nexys4_Master.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/rafa/Dropbox/Aulas/Pos/2014/LogicaProgramavel/Exemplos/05-Concorrente/05-Mux-Simples/Mux-Simples.cache/wt [current_project]
set_property parent.project_dir /home/rafa/Dropbox/Aulas/Pos/2014/LogicaProgramavel/Exemplos/05-Concorrente/05-Mux-Simples [current_project]
catch { write_hwdef -file toplevelmux.hwdef }
synth_design -top toplevelmux -part xc7a100tcsg324-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off
write_checkpoint toplevelmux.dcp
report_utilization -file toplevelmux_utilization_synth.rpt -pb toplevelmux_utilization_synth.pb
