# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_vhdl -library xil_defaultlib /home/rafa/aula1/aula1.srcs/sources_1/new/aula1.vhd
read_xdc /home/rafa/aula1/aula1.srcs/constrs_1/new/io_basicos.xdc
set_property used_in_implementation false [get_files /home/rafa/aula1/aula1.srcs/constrs_1/new/io_basicos.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/rafa/aula1/aula1.cache/wt [current_project]
set_property parent.project_dir /home/rafa/aula1 [current_project]
catch { write_hwdef -file aula1.hwdef }
synth_design -top aula1 -part xc7a100tcsg324-1
write_checkpoint aula1.dcp
report_utilization -file aula1_utilization_synth.rpt -pb aula1_utilization_synth.pb
